/* Shared Trainers Data */
const trainersData = [
  {
    id: 1,
    name: 'Rahim Uddin',
    specialty: 'Strength & Powerlifting',
    image: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=500&q=80',
    rate: 3000,
    experience: '8 years',
    bio: 'Rahim is a certified strength coach specializing in powerlifting and bodybuilding. He has helped over 200 clients build serious muscle and strength. His training philosophy focuses on progressive overload and proper form above everything.',
    phone: '+880 1711-111111',
    whatsapp: '+8801711111111',
    instagram: 'https://instagram.com/rahim_fitness',
    facebook: 'https://facebook.com/rahim.fitness',
    certifications: ['NSCA Certified Strength Coach', 'Sports Nutrition Certificate', 'First Aid & CPR'],
    achievements: ['National Powerlifting Champion 2022', 'Trained 200+ clients', 'Certified Sports Nutritionist']
  },
  {
    id: 2,
    name: 'Shakib Al Hasan',
    specialty: 'Weight Loss & HIIT',
    image: 'https://images.unsplash.com/photo-1571388208497-71bedc66e932?w=500&q=80',
    rate: 2500,
    experience: '6 years',
    bio: 'Shakib is a high-intensity training expert who has helped hundreds of people lose weight and get fit. His HIIT and circuit training programs are designed to burn maximum fat while building lean muscle. He believes fitness should be fun and challenging.',
    phone: '+880 1722-222222',
    whatsapp: '+8801722222222',
    instagram: 'https://instagram.com/shakib_hiit',
    facebook: 'https://facebook.com/shakib.hiit',
    certifications: ['ACE Certified Personal Trainer', 'HIIT Specialist', 'TRX Certified'],
    achievements: ['500+ transformations', 'HIIT Workshop Leader', 'Online fitness influencer']
  },
  {
    id: 3,
    name: 'Farhan Ahmed',
    specialty: 'Bodybuilding & Physique',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    rate: 3500,
    experience: '10 years',
    bio: 'Farhan is a competitive bodybuilder with 10 years of training experience. He specializes in contest prep, muscle hypertrophy, and aesthetic physique development. His methodical approach combines science-based training with practical nutrition.',
    phone: '+880 1733-333333',
    whatsapp: '+8801733333333',
    instagram: 'https://instagram.com/farhan_physique',
    facebook: 'https://facebook.com/farhan.physique',
    certifications: ['ISSA Bodybuilding Specialist', 'Precision Nutrition Level 1', 'Contest Prep Coach'],
    achievements: ['Mr. Khulna 2021 & 2023', 'IFBB Amateur competitor', '10+ years coaching']
  },
  {
    id: 4,
    name: 'Tanvir Rahman',
    specialty: 'Functional & CrossFit',
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=500&q=80',
    rate: 2800,
    experience: '5 years',
    bio: 'Tanvir brings the intensity of CrossFit with the practicality of functional training. His programs improve overall athleticism, mobility, and real-world strength. He is a Level 2 CrossFit trainer with a passion for helping beginners break through barriers.',
    phone: '+880 1744-444444',
    whatsapp: '+8801744444444',
    instagram: 'https://instagram.com/tanvir_crossfit',
    facebook: 'https://facebook.com/tanvir.crossfit',
    certifications: ['CrossFit Level 2 Trainer', 'Mobility Specialist', 'Kettlebell Certified'],
    achievements: ['Top CrossFit athlete in Khulna', 'Functional fitness workshops', 'Community leader']
  },
  {
    id: 5,
    name: 'Imran Khan',
    specialty: 'Martial Arts & Boxing',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80',
    rate: 2500,
    experience: '7 years',
    bio: 'Imran combines martial arts discipline with fitness training. His boxing and kickboxing classes are among the most popular at Flex Fit. He focuses on building confidence, stamina, and self-defense skills alongside physical fitness.',
    phone: '+880 1755-555555',
    whatsapp: '+8801755555555',
    instagram: 'https://instagram.com/imran_boxing',
    facebook: 'https://facebook.com/imran.boxing',
    certifications: ['Boxing Coach Certified', 'Muay Thai Instructor', 'Self Defense Expert'],
    achievements: ['Regional Boxing Champion', 'Trained 150+ students', 'Black belt in Karate']
  },
  {
    id: 6,
    name: 'Nusrat Jahan',
    specialty: 'Yoga & Flexibility',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&q=80',
    rate: 2000,
    experience: '6 years',
    bio: 'Nusrat is a certified yoga instructor who helps clients improve flexibility, reduce stress, and build core strength through mindful movement. Her classes are perfect for beginners and advanced practitioners alike.',
    phone: '+880 1766-666666',
    whatsapp: '+8801766666666',
    instagram: 'https://instagram.com/nusrat_yoga',
    facebook: 'https://facebook.com/nusrat.yoga',
    certifications: ['RYT-200 Yoga Alliance', 'Pilates Instructor', 'Meditation Coach'],
    achievements: ['500+ yoga students', 'Wellness retreat organizer', 'Online yoga community leader']
  }
];
